"use client"

import './globals.css'

// export const metadata = {
//   title: 'Chamber',
// description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark:bg-gray-900">{children}</body>
    </html>
  )
}
