"use client"

import { DarkMode, useTheme } from '@/hooks/useTheme';
import './globals.css'
import clsx from 'clsx';

// export const metadata = {
//   title: 'Chamber',
// description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [darkMode, toggleTheme, isInitialized] = useTheme();

  return (
    <html lang="en" className={clsx(darkMode ? 'dark' : '')}>
      <DarkMode.Provider value={[darkMode, toggleTheme, isInitialized]}>
        <body className="dark:bg-gray-900 bg-gray-200">{isInitialized && children}</body>
      </DarkMode.Provider>
    </html>
  )
}
